### PR TITLE
create/resources: Fix instances state detection

### LINKED ISSUE #125: Filtering instances by state code doesn't work - multiple state filters are not in OR relation
In theory, AWS API should merge the filters with the same name by OR relation. I don't know why, but that compeletely isn't true when using aws-sdk-go.

We have a lot of multiple instances with the same name.

See the logs (I've added filters and instances printing to clarify the situation:

```
ice/create/service.go:161","info":"successfully created third-party resource","time":"17-04-20 11:35:47.119"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:636","info":"starting watch","time":"17-04-20 11:35:47.119"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:170","info":"creating cluster 'michal'","time":"17-04-20 11:36:05.315"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:205","info":"created keypair 'michal'","time":"17-04-20 11:36:06.049"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:210","info":"waiting for k8s secrets...","time":"17-04-20 11:36:06.049"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:269","info":"bucket '292127003750-g8s-michal-customer' already exists, reusing","time":"17-04-20 11:36:08.212"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:287","info":"vpc for cluster 'michal' already exists, reusing","time":"17-04-20 11:36:08.373"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:305","info":"gateway for cluster 'michal' already exists, reusing","time":"17-04-20 11:36:08.445"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:325","info":"security group 'michal' already exists, reusing","time":"17-04-20 11:36:08.632"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:342","info":"route table already exists, reusing","time":"17-04-20 11:36:08.726"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:361","info":"public subnet for cluster 'michal' already exists, reusing","time":"17-04-20 11:36:08.843"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:385","info":"private subnet for cluster 'michal' already exists, reusing","time":"17-04-20 11:36:09.076"}
[{
  Name: "instance-state-code",
  Values: ["16"]
} {
  Name: "instance-state-code",
  Values: ["0"]
} {
  Name: "tag:Cluster",
  Values: ["michal"]
} {
  Name: "tag:Name",
  Values: ["michal-master-0"]
}]
{

}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:847","info":"instance 'michal-master-0' reserved","time":"17-04-20 11:36:18.187"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:852","info":"instance 'michal-master-0' tagged","time":"17-04-20 11:36:18.187"}
{"caller":"github.com/giantswarm/aws-operator/service/create/loadbalancer.go:40","debug":"created ELB 'michal-cluster'","time":"17-04-20 11:36:18.766"}
{"caller":"github.com/giantswarm/aws-operator/service/create/loadbalancer.go:65","debug":"hosted zone 'cluster.giantswarm.io' already exists, reusing","time":"17-04-20 11:36:19.252"}
{"caller":"github.com/giantswarm/aws-operator/service/create/loadbalancer.go:79","debug":"created or reused DNS record for ELB","time":"17-04-20 11:36:19.396"}
{"caller":"github.com/giantswarm/aws-operator/service/create/loadbalancer.go:81","debug":"waiting for masters to be ready...","time":"17-04-20 11:36:19.396"}
{"caller":"github.com/giantswarm/aws-operator/service/create/loadbalancer.go:98","debug":"instances registered with ELB","time":"17-04-20 11:36:35.018"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:423","info":"created load balancer","time":"17-04-20 11:36:35.018"}
[{
  Name: "instance-state-code",
  Values: ["16"]
} {
  Name: "instance-state-code",
  Values: ["0"]
} {
  Name: "tag:Cluster",
  Values: ["michal"]
} {
  Name: "tag:Name",
  Values: ["michal-worker-0"]
}]
{

}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:847","info":"instance 'michal-worker-0' reserved","time":"17-04-20 11:36:36.274"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:852","info":"instance 'michal-worker-0' tagged","time":"17-04-20 11:36:36.274"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:451","info":"cluster 'michal' processed","time":"17-04-20 11:36:36.274"}
```

At the same time, there are actually a lot of `michal-master-0` and `michal-worker-0` instances.

I think that https://github.com/giantswarm/aws-operator/pull/113 should be reverted

### PR DESCRIPTION
**Pull request by nhlfr**
Applying filters with the same keys in aws-sdk-go doesn't merge them in OR relation.

Fixes #125

### CODE REVIEW

File: resources/aws/instance.go [hunk 1]
```diff
@@ -42,60 +42,90 @@ type Instance struct {
...
+		}
+	}
+
+	return nil, microerror.MaskAny(instanceFindError)
+}
+
+func (i *Instance) checkIfExists() (bool, error) {
+	instance, err := i.findExisting()
+	if err != nil {
+		if strings.Contains(err.Error(), instanceFindError.Error()) {
```
Comment (xh3b4sd) [inline resources/aws/instance.go]: We agreed on not comparing strings. Please use an error matcher. See for instance https://github.com/giantswarm/kubernetesd/blob/master/service/error.go.

**Comment by nhlfr** [comment]
@xh3b4sd Sorry, I was maybe a little bit unclear.

The logical problem is that the instances were not removed during cluster deletions at all.

That's because our filter looked for the instances with `Running` *AND* `Pending` state, instead of `Running` *OR*  `Pending`. It's probably some issue with aws-sdk-go, because in theory, calling the AWS API with two `instance-state` filters should involve the OR relation. I think it's better to deal with statuses like in this pull request.
