### PR TITLE
resources: Log retry actions

### LINKED ISSUE #174: No communication when stuck in `backoff.Retry`
When the operator gets stuck in a Retry loop, all the user sees is a frozen application, with no visibility into what is causing the operation to fail.

This is because we don't perform logging from `resource`s.

We could add a `Logger` to the aws resources like `ELB`.

### PR DESCRIPTION
**Pull request by nhlfr**
This commits brings log messages when we retry to create or delete some resource and injects logger to resources.

Fixes #174

### CODE REVIEW

File: resources/aws/gateway.go [hunk 1]
```diff
@@ -122,6 +127,7 @@ func (g *Gateway) Delete() error {
 		if _, err := g.Clients.EC2.DeleteInternetGateway(&ec2.DeleteInternetGatewayInput{
 			InternetGatewayId: gateway.InternetGatewayId,
 		}); err != nil {
+			g.Logger.Log("error", fmt.Sprintf("deleting gateway failes, retrying %v", errgo.Details(err)))
```
Comment (JosephSalisbury) [inline resources/aws/gateway.go]: i hate nitpicking like this, but `failes` -> `failed`

Comment (nhlfr) [inline resources/aws/gateway.go]: done

File: resources/aws/instance.go [hunk 2]
```diff
@@ -150,6 +154,7 @@ func (i *Instance) CreateOrFail() error {
 			SubnetId: aws.String(i.SubnetID),
 		})
 		if err != nil {
+			i.Logger.Log("error", fmt.Sprintf("creating instance failed, retrying: %v", errgo.Details(err)))
```
Comment (xh3b4sd) [inline resources/aws/instance.go]: FYI, this is not how this should be used. See https://godoc.org/github.com/cenkalti/backoff#RetryNotify. There is a notifier that should be configured. This notifier can deal with logging and metrics and the like.
