### PR TITLE
resource: Make logic about creating and reusing resources more visible

### LINKED ISSUE #49: create: use backoff package instead of custom code
Capturing https://github.com/giantswarm/aws-operator/pull/47#discussion_r105929524

### LINKED ISSUE #53: S3 bucket isn't created automatically
Which causes the following error:

```
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:177","info":"successfully created third-party resource","time":"17-03-15 15:43:40.237"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:274","info":"starting watch","time":"17-03-15 15:43:40.237"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:186","info":"creating cluster 'test-michal'","time":"17-03-15 15:43:40.238"}
{"caller":"github.com/giantswarm/aws-operator/service/create/keypair.go:51","info":"keypair 'test-michal' exists, reusing","time":"17-03-15 15:43:40.452"}
{"caller":"github.com/giantswarm/aws-operator/service/create/policy.go:68","info":"role 'example-cluster-EC2-K8S-Role' exists, reusing","time":"17-03-15 15:43:41.911"}
{"caller":"github.com/giantswarm/aws-operator/service/create/policy.go:93","info":"instance profile 'example-cluster-EC2-K8S-Role' exists, reusing","time":"17-03-15 15:43:42.627"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:243","error":"NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: D98777358A8C255F","time":"17-03-15 15:43:43.398"}
```

### LINKED ISSUE #55: Roles/policies should be reused
The following error:

```
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:177","info":"successfully created third-party resource","time":"17-03-15 15:58:57.397"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:282","info":"starting watch","time":"17-03-15 15:58:57.397"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:186","info":"creating cluster 'test-michal'","time":"17-03-15 15:58:57.399"}
{"caller":"github.com/giantswarm/aws-operator/service/create/keypair.go:51","info":"keypair 'test-michal' exists, reusing","time":"17-03-15 15:58:57.588"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:216","error":"error creating role: EntityAlreadyExists: Role with name example-cluster-EC2-K8S-Role already exists.\n\tstatus code: 409, request id: 4cc1d5d5-0998-11e7-a3f0-05517d261dae","time":"17-03-15 15:58:58.607"}
```

### PR DESCRIPTION
**Pull request by nhlfr**
Introduce the resources/ pkg which provides an interface for resources which are able to be created or reused and use it in create operator.

Fixes #55
Fixes #53
Fixes #49

### CODE REVIEW

File: service/create/policy.go [hunk 1]
```diff
@@ -63,7 +64,11 @@ func createRole(svc *iam.IAM, kmsKeyArn, s3Bucket, clusterID string) error {
 		RoleName:                 aws.String(clusterRoleName),
 		AssumeRolePolicyDocument: aws.String(AssumeRolePolicyDocument),
 	}); err != nil {
-		return err
+		if aerr, ok := err.(awserr.Error); ok && aerr.Code() == iam.ErrCodeEntityAlreadyExistsException {
+			s.logger.Log("info", fmt.Sprintf("role '%s' exists, reusing", clusterRoleName))
+		} else {
+			return err
```
Comment (xh3b4sd) [inline service/create/policy.go]: We tend to use error masking with the microkit error library. This makes debugging more easy when shit hits the fan.

File: service/create/policy.go [hunk 2]
```diff
@@ -77,14 +82,18 @@ func createRole(svc *iam.IAM, kmsKeyArn, s3Bucket, clusterID string) error {
...
-func createInstanceProfile(svc *iam.IAM, clusterID string) (string, error) {
+func (s *Service) createInstanceProfile(svc *iam.IAM, clusterID string) (string, error) {
 	clusterRoleName := fmt.Sprintf("%s-%s", clusterID, RoleNameTemplate)
 	clusterProfileName := fmt.Sprintf("%s-%s", clusterID, ProfileNameTemplate)
 
 	if _, err := svc.CreateInstanceProfile(&iam.CreateInstanceProfileInput{
 		InstanceProfileName: aws.String(clusterProfileName),
 	}); err != nil {
-		return "", err
+		if aerr, ok := err.(awserr.Error); ok && aerr.Code() == iam.ErrCodeEntityAlreadyExistsException {
```
Comment (xh3b4sd) [inline service/create/policy.go]: I think it would make sense to have a `IsEC2FooAlreadyExists(error) bool` function.

**Comment by nhlfr** [comment]
@iaguis then we have to agree on some graceful way of failure when the policy exists. When you're restarting aws-operator after it created a cluster once, it will try to recreate it again. Having just `error: cannot create profile` or anything like that in logs would look scary in the situation when it's totally fine, because aws-operator is just processing the cluster which already exists.

**Comment by nhlfr** [comment]
@iaguis @asymmetric @xh3b4sd PTAL again :)

File: client/aws/errors.go [hunk 3]
```diff
@@ -1,5 +1,7 @@
 package aws
 
 const (
-	KeyPairDuplicate = "InvalidKeyPair.Duplicate"
+	BucketAlreadyExists     = "BucketAlreadyExists"
+	BucketAlreadyOwnedByYou = "BucketAlreadyOwnedByYou"
```
Comment (xh3b4sd) [inline client/aws/errors.go]: Who is `You` in that case?

File: resources/aws/bucket.go [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+}
+
+func (b *Bucket) CreateOrFail() error {
+	if _, err := b.Clients.S3.CreateBucket(&s3.CreateBucketInput{
+		Bucket: aws.String(b.Name),
+	}); err != nil {
+		return microerror.MaskAny(err)
+	}
+
+	if err := b.Clients.S3.WaitUntilBucketExists(&s3.HeadBucketInput{
```
Comment (xh3b4sd) [inline resources/aws/bucket.go]: Is there a timeout? The method is called `OrFail`. So in what case does it fail?

File: resources/aws/keypair.go [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+}
+
+func NewFSKeyPairProvider(pubKeyFile string) *FSKeyPairProvider {
+	return &FSKeyPairProvider{
+		pubKeyFile: pubKeyFile,
+	}
+}
+
+func (f *FSKeyPairProvider) pubKeyContent() ([]byte, error) {
+	return ioutil.ReadFile(f.pubKeyFile)
```
Comment (xh3b4sd) [inline resources/aws/keypair.go]: Lets have a hangout about this FS thing.

File: resources/aws/instance.go [hunk 6]
```diff
@@ -0,0 +1,180 @@
...
+		}
+		return nil
+	}
+
+	if err := backoff.Retry(reserveOperation, backoff.NewExponentialBackOff()); err != nil {
+		return microerror.MaskAny(err)
+	}
+
+	if _, err := i.Clients.EC2.CreateTags(&ec2.CreateTagsInput{
+		Resources: []*string{reservation.Instances[0].InstanceId},
```
Comment (xh3b4sd) [inline resources/aws/instance.go]: I am not sure there is always at least one instance to prevent this code panicing. I would like to be more defensive here.

File: client/aws/errors.go (hunk 3 above)
Comment (nhlfr) [inline client/aws/errors.go]: `Ỳou` is the user in AWS/S3. This error occurs if the bucket already exists and was created by your AWS user.

File: resources/aws/keypair.go (hunk 5 above)
Comment (nhlfr) [inline resources/aws/keypair.go]: Sure, but if your concern is to not rely unit tests on FS, then this Provider interface solves the problem.

File: resources/aws/instance.go (hunk 6 above)
Comment (nhlfr) [inline resources/aws/instance.go]: Sure, I can do a forloop here.

**Comment by nhlfr** [comment]
The main purpose of this PR is to be aware that the cluster is inconsistent if:

- the KMS keys already existed and instances did not - since KMS keys are not reusable, it means that we cannot encrypt assets for the instances we need to create
- the KMS keys did not exist, but instanced existed - that means that during the previous run of aws-operator something bad happened to the keys and most probably the assets for the instances were not encrypted properly

Since we are in the early stages of development, we often have situations where our code creates inconsistent clusters and it's really painful to check whether everything exists (or not) in AWS web interface. This code and information that the cluster is wrong and we need to re-create it will IMO simplify the things.

Also, the reason why I introduced the interface for resources is that I would like to have a clear logic about creating, creating or reusing and deleting resources. And I thought that is kinda similar to your idea of having interface for resource reconciliation which you wrote about some time ago.

Let me know if it addresses your doubts about the goal of this PR. I will try to make the PR description more descriptive.

File: resources/aws/bucket.go (hunk 4 above)
Comment (nhlfr) [inline resources/aws/bucket.go]: AWS SDK hardcodes the number of 20 attempts. https://github.com/aws/aws-sdk-go/blob/master/service/s3/waiters.go#L87 So, if after 20 iterations with 5 second delays the bucket doesn't exist, the error is returned.

**Comment by nhlfr** [comment]
I hope that this picture nakes a "failed cluster detection" logic better http://i.imgur.com/DSJwLH8.jpg

File: resources/aws/instance.go (hunk 6 above)
Comment (nhlfr) [inline resources/aws/instance.go]: done

File: client/aws/errors.go (hunk 3 above)
Comment (xh3b4sd) [inline client/aws/errors.go]: Cool. Maybe put this as a comment.

File: resources/aws/keypair.go (hunk 5 above)
Comment (xh3b4sd) [inline resources/aws/keypair.go]: I see. This is my weak brain I talked about before. I did not realize that it is the `FSKeyPairProvider`. I did not get the `FS` part here when I was scanning the code. All good. Thanks for bearing with me.

**Comment by xh3b4sd** [comment]
You described scenarios in which we create inconsistent state in AWS. I guess for now we need to manually recreate the cluster which means deleting all resources in AWS and creating it again. Lets track an issue in the boards to automate this so the operator is at some point able to deal with such situations on its own.
