### PR TITLE
Fix VPC deletion

### LINKED ISSUE #109: Deleting subnet fails
There seems to be a timing issue while deleting subnets:

```
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:522","error":"could not delete public subnet: [{/home/asymmetric/code/go/src/github.com/giantswarm/aws-operator/resources/aws/subnet.go:111: } {DependencyViolation: The subnet 'subnet-7996df11' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 91a792e2-a97a-4675-8ef8-afa88825400c}]","time":"17-04-13 14:10:43.452"}
```

The subnets can be deleted by hand without problems afterwards. So it seems that in between these two attempts, something got freed up.

/cc @nhlfr

### PR DESCRIPTION
**Pull request by nhlfr**
Fixes #109

### CODE REVIEW

File: resources/aws/gateway.go [hunk 1]
```diff
@@ -108,15 +110,45 @@ func (g *Gateway) Delete() error {
...
+		return nil
+	}
+	if err := backoff.Retry(deleteOperation, backoff.NewExponentialBackOff()); err != nil {
 		return microerror.MaskAny(err)
 	}
 
 	return nil
 }
 
+func (g *Gateway) Get() error {
```
Comment (xh3b4sd) [inline resources/aws/gateway.go]: Why is `Get` manipulating the internal state? When we discussed the interface I thought we agreed on lookup functions returning what they are supposed to get. This here looks like the lookup tries to find the actual gateway ID. So I would expect to see something like this without manipulating the internal ID. Having getters manipulating internal state is counterintuitive IMO. 

```
func (g *Gateway) GetID() (string, error)  
```

File: resources/aws/subnet.go [hunk 2]
```diff
@@ -100,17 +103,23 @@ func (s *Subnet) CreateOrFail() error {
 }
 
 func (s *Subnet) Delete() error {
```
Comment (xh3b4sd) [inline resources/aws/subnet.go]: IMO `Subnet` is a genetal logic provider. Thus `Delete` should expect an ID argument identifying the subnet to delete. This separates logic from data structures.

File: resources/aws/bucket.go [hunk 3]
```diff
@@ -8,13 +8,18 @@ import (
...
+	"github.com/giantswarm/aws-operator/resources"
 )
 
 type Bucket struct {
 	Name string
 	AWSEntity
 }
 
+// Implement ReusableResource.
+var _ = resources.ReusableResource(&Bucket{})
```
Comment (nhlfr) [inline resources/aws/bucket.go]: This is ensuring that the given struct is implementing the interface.

Comment (xh3b4sd) [inline resources/aws/bucket.go]: Why do we need to ensure this here? It should be ensured where it is actually being used. So this should be good enough.

Comment (asymmetric) [inline resources/aws/bucket.go]: Is this better than just declaring `bucket := resources.ReusableResource` like you were doing before?

Also, is it idiomatic Go?

**Comment by asymmetric** [comment]
Towards #123.

File: resources/aws/subnet.go (hunk 2 above)
Comment (nhlfr) [inline resources/aws/subnet.go]: Umm... IMO `Subnet` is a data structurem which we fill with the data and send them to AWS API. `Delete` is a method which we run on the single instance.

File: resources/aws/bucket.go (hunk 3 above)
Comment (nhlfr) [inline resources/aws/bucket.go]: It's a hack from Kubernetes, they're doing that often.

I had a feeling that we produce a lot of ugly looking code by doing the following in service.go:

```
var foo resources.ResourceXYZ
foo = awsresources.Subnet{}
```

and I think it's better to ensure that struct implements interface in the module it's defined, and just use instances of structs in service.go. But whatever, if it really hurts you that much, I can go back to the old solution.

Comment (asymmetric) [inline resources/aws/bucket.go]: Do we even need to confirm we conform to the interface in this case? Honest question.

If we're not using the interface type as an abstraction over the implementations anywhere (e.g. as an argument to a function) then what do we need the interface for?

If we call a method on a struct that's not there, we'll get a compile error anyway.

Or am I missing something obvious?

Comment (nhlfr) [inline resources/aws/bucket.go]: Examples from Kubernetes:

https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/eviction.go#L66
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/storage.go#L99
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/extensions/controller/storage/storage.go#L57
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/exec/admission.go#L56
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/limitranger/admission.go#L170-L171
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/namespace/autoprovision/admission.go#L48-L49

Comment (nhlfr) [inline resources/aws/bucket.go]: For now maybe we are not using those interfaces anywhere, but one of the biggest concerns we had some time ago was abstracting resources (i.e. for potential re-usage in operatorkit) and lack of uniqueness in resource methods.

Comment (xh3b4sd) [inline resources/aws/bucket.go]: IMO interfaces should be best defined where they are used, not where they are implemented. So it is fine to just deal with structs and have the abstraction where interfaces are used.

File: resources/aws/subnet.go (hunk 2 above)
Comment (xh3b4sd) [inline resources/aws/subnet.go]: Why does a data structure has an API client? Data structures hold information. Services, managers, providers, etc. implement business logic. This is why we talked about the interface and I was under the impression we agreed on this. So in my opinion a good design would be to have a data structure holding information like some ID. This data structure or the plain ID can be provided to some service that implements business logic like deletion. The service has API clients configured. The service's `Delete` method expects at least one argument, the data structure or the ID. 

Since this here takes already longer than expected I would say lets go with this and do further improvements later on. Lets make sure the more important things get addressed.

Comment (nhlfr) [inline resources/aws/subnet.go]: OK, I agree, thanks for clarification. Yes, separating those things later would be good.

**Comment by nhlfr** [comment]
@xh3b4sd PTAL again
