### PR TITLE
resources/service: Don't fail if master instance(s) already exist(s)

### LINKED ISSUE #83: aws-operator fails during processing the existing master node
When aws-operator processes the existing cluster, the following error occurs:
```
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:289","error":"master nodes had invalid instance IDs","time":"17-03-27 13:26:28.827"}
```

This started to happen after introducing the elastic IP functionality.

### PR DESCRIPTION
**Pull request by nhlfr**
Fixes #83

### CODE REVIEW

File: resources/aws/elasticip.go [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+	"fmt"
+
+	"github.com/aws/aws-sdk-go/aws"
+	"github.com/aws/aws-sdk-go/service/ec2"
+	microerror "github.com/giantswarm/microkit/error"
+)
+
+const (
+	allocationID = "eipalloc-cc1657a5"
+	elasticIP    = "35.158.16.27"
```
Comment (xh3b4sd) [inline resources/aws/elasticip.go]: I assume this is for testing purposes and only because we are in an early stage.

Comment (nhlfr) [inline resources/aws/elasticip.go]: Yes, that's right.
