### PR TITLE
resources: Switch from backoff.Retry to backoff.RetryNotify

### LINKED ISSUE #174: No communication when stuck in `backoff.Retry`
When the operator gets stuck in a Retry loop, all the user sees is a frozen application, with no visibility into what is causing the operation to fail.

This is because we don't perform logging from `resource`s.

We could add a `Logger` to the aws resources like `ELB`.

### PR DESCRIPTION
**Pull request by nhlfr**
Fixes #174

### CODE REVIEW

File: resources/aws/backoff.go [hunk 1]
```diff
@@ -25,3 +28,9 @@ func NewCustomExponentialBackoff() *backoff.ExponentialBackOff {
 
 	return b
 }
+
+func NewNotify(logger micrologger.Logger, operationName string) func(error, time.Duration) {
+	return func(err error, delay time.Duration) {
+		logger.Log("error", fmt.Sprintf("%s failed, retrying with delay %.0fm%.0fs: %v", operationName, delay.Minutes(), delay.Seconds(), errgo.Details(err)))
```
Comment (xh3b4sd) [inline resources/aws/backoff.go]: `delay.String()` is not good enough?

Comment (nhlfr) [inline resources/aws/backoff.go]: Not really. `delay.String()` shows milliseconds as well:
https://play.golang.org/p/BLbNfkpaHh

Comment (xh3b4sd) [inline resources/aws/backoff.go]: I see. That is really not that handy.
